// ChocoManager
using System.Collections.Generic;
using UnityEngine;

public class ChocoManager : MonoBehaviour
{
    public static void FillSonglist(List<SongInfo> Chocolist)
    {
        Chocolist.Add(new SongInfo("#thatPOWER", "will.i.am ft. Justin Bieber", "2013", "Dance Crew", "Just Dance 2014", "Thatpowerquat"));
        Chocolist.Add(new SongInfo("24K Magic", "Bruno Mars", "2016", "Duet", "Just Dance 2018", "24k_cover_generic"));
        Chocolist.Add(new SongInfo("99 Luftballons", "Nena", "1983", "Duet", "Just Dance 2014", "Luftballons"));
        Chocolist.Add(new SongInfo("Acceptable in the 80s", "Calvin Harris", "2007", "Solo", "Just Dance", "Acceptable"));
        Chocolist.Add(new SongInfo("Adeyyo", "Ece Seçkin", "2016", "Solo", "Just Dance 2019", "Adeyyo_cover_generic"));
        Chocolist.Add(new SongInfo("Ain’t My Fault", "Zara Larson", "2016", "Solo", "Just Dance Unlimited", "AintMy_Cover_Generic"));
        Chocolist.Add(new SongInfo("Airplanes ", "B.o.B. ft. Hayley Williams of Paramore", "2010", "Solo", "Just Dance 3", "Airplanes_jdnow"));
        Chocolist.Add(new SongInfo("All About That Bass", "Meghan Trainor", "2014", "Solo", "Just Dance 2016", "Aboutthatbass_cover_generic"));
        Chocolist.Add(new SongInfo("All About Us", "Jordan Fisher", "2016", "Trio", "Just Dance 2017", "Allaboutus"));
        Chocolist.Add(new SongInfo("All You Gotta Do (Is Just Dance)", "The Just Dance Band", "2017", "Solo", "Just Dance 2018", "Allyougotta_cover_generic"));
        Chocolist.Add(new SongInfo("Am I Wrong", "Nico & Vinz", "2013", "Solo", "Just Dance Unlimited", "Amiwrong"));
        Chocolist.Add(new SongInfo("Amazing Girl", "The Girly Team", "2017", "Solo", "Just Dance 2018 (Kids Mode)", "Missamazingkids_cover_generic"));
        Chocolist.Add(new SongInfo("American Girl", "Bonnie McKee", "2013", "Solo", "Just Dance 2014", "Americangirldlc"));
        Chocolist.Add(new SongInfo("Animals", "Martin Garrix", "2013", "Duet", "Just Dance 2016", "Animals"));
        Chocolist.Add(new SongInfo("Another One Bites the Dust", "Queen", "1980", "Dance Crew", "Just Dance 2018", "Anotherone_cover_generic"));
        Chocolist.Add(new SongInfo("Apache (Jump On It) ", "The Sugarhill Gang", "1981", "Solo", "Just Dance 3", "Apachejdn"));
        Chocolist.Add(new SongInfo("Applause", "Lady Gaga", "2013", "Solo", "Just Dance 2014", "Limagolf1"));
        Chocolist.Add(new SongInfo("Aquarius/Let the Sunshine In ", "The 5th Dimension (The Sunlight Shakers)", "1969", "Duet", "Just Dance 2014", "Aquarius"));
        Chocolist.Add(new SongInfo("Aserejé (The Ketchup Song)", "Las Ketchup", "2002", "Duet", "Just Dance 4", "Ketchupsong"));
        Chocolist.Add(new SongInfo("Automaton", "Jamiraqui", "2017", "Solo", "Just Dance 2018", "Automaton_cover_generic"));
        Chocolist.Add(new SongInfo("Baby Girl", "Reggaeton", "2009", "Solo", "Just Dance 2", "Baby_girl_jdn"));
        Chocolist.Add(new SongInfo("Baby One More Time", "Britney Spears (The Girly Team)", "1998", "Dance Crew", "Just Dance 3", "Baby_one_more_time_jdn"));
        Chocolist.Add(new SongInfo("Bad Liar", "Selena Gomez", "2017", "Solo", "Just Dance 2018", "Badliar_cover_generic"));
        Chocolist.Add(new SongInfo("Bad Romance", "Lady Gaga", "2009", "Trio", "Just Dance 2015", "Badromance"));
        Chocolist.Add(new SongInfo("Bailar", "Deorro ft. Elvis Crespo", "2016", "Solo", "Just Dance 2017", "Bailar"));
        Chocolist.Add(new SongInfo("Balkan Blast Remix", "Ari Pulkkinen (Angry Birds)", "2015", "Dance Crew (Angled)", "Just Dance 2016", "Angrybirds"));
        Chocolist.Add(new SongInfo("Bang", "Anitta", "2015", "Solo", "Just Dance 2017", "Bang"));
        Chocolist.Add(new SongInfo("Bang Bang", "Jessie J, Ariana Grande and Nicki Minaj", "2014", "Dance Crew", "Just Dance 2015", "Balance_cover_generic"));
        Chocolist.Add(new SongInfo("Bang Bang Bang", "BIGBANG", "2015", "Trio", "Just Dance 2019", "Bang2019_cover_generic"));
        Chocolist.Add(new SongInfo("Barbie Girl", "Aqua (Countdown Dee’s Hit Explosion)", "1997", "Duet", "Just Dance 2", "Barbiegirl_now"));
        Chocolist.Add(new SongInfo("Beauty And A Beat", "Justin Bieber ft. Nicki Minaj", "2012", "Solo", "Just Dance 4", "Beautyandabeatdlc"));
        Chocolist.Add(new SongInfo("Beep Beep I’m A Sheep", "LilDeuceDeuce ft. BlackGryph0n & TomSka", "2017", "Solo", "Just Dance 2018", "Beepbeep_cover_generic"));
        Chocolist.Add(new SongInfo("Better When I'm Dancin'", "Meghan Trainor", "2015", "Solo", "Just Dance Unlimited", "Betterwheni'm_jdnow"));
        Chocolist.Add(new SongInfo("Beware of the Boys (Mundian To Bach Ke)", "Panjabi MC", "1998", "Dance Crew", "Just Dance 4", "Bewareof"));
        Chocolist.Add(new SongInfo("Big Girl (You Are Beautiful)", "MIKA", "2007", "Solo", "Just Dance 2", "Biggirl"));
        Chocolist.Add(new SongInfo("Birthday", "Katy Perry", "2013", "Solo", "Just Dance 2015", "Birthday"));
        Chocolist.Add(new SongInfo("Blame", "Calvin Harris ft. John Newman", "2014", "Solo", "Just Dance 2016", "Blame"));
        Chocolist.Add(new SongInfo("Blow Your Mind (Mwah)", "Dua Lipa", "2016", "Solo", "Just Dance 2018", "Blowyourmind_cover_generic 1"));
        Chocolist.Add(new SongInfo("Blue (Da Ba Dee)", "Eiffel 65 (Hit The Electro Beat)", "1999", "Solo", "Just Dance 2018", "Blue_cover_generic"));
        Chocolist.Add(new SongInfo("Blurred Lines", "Robin Thicke feat. Pharrell Williams", "2013", "Duet", "Just Dance 2014", "Blurredlines"));
        Chocolist.Add(new SongInfo("Bonbon", "Era Istrefi", "2016", "Solo", "Just Dance 2017", "Bonbon"));
        Chocolist.Add(new SongInfo("Boogie Wonderland", "Earth, Wind and Fire ft. The Emotions (Groove Century)", "1979", "Dance Crew", "Just Dance 3", "Boogiewonderquat"));
        Chocolist.Add(new SongInfo("Boom Boom", "Iggy Azalea ft. Zedd", "2017", "Trio", "Just Dance 2018", "Copperhead_cover_generic"));
        Chocolist.Add(new SongInfo("Boom Clap", "Charli XCX", "2014", "Solo", "Just Dance 2015", "Boomclapdlc_cover_generic"));
        Chocolist.Add(new SongInfo("Boom", "Reggaeton Storm", "2005", "Solo", "Just Dance 3", "Boomdlc"));
        Chocolist.Add(new SongInfo("Born This Way", "Lady Gaga", "2011", "Trio", "Just Dance 2016", "Bornthisway"));
        Chocolist.Add(new SongInfo("Boys (Summertime Love)", "Sabrina (The Lemon Cubes)", "1987", "Trio", "Just Dance 2016", "Boys_boys"));
        Chocolist.Add(new SongInfo("Break Free", "Ariana Grande ft. Zedd", "2014", "Solo", "Just Dance 2015", "Breakfreedlc"));
        Chocolist.Add(new SongInfo("Bubble Pop!", "HyunA", "2011", "Trio", "Just Dance 2018", "Bubblepop_cover_generic"));
        Chocolist.Add(new SongInfo("Built For This", "Becky G", "2014", "Solo", "Just Dance 2015", "Builtforthis"));
        Chocolist.Add(new SongInfo("C'Mon", "Ke$ha", "2012", "Duet", "Just Dance 2014", "Cmon"));
        Chocolist.Add(new SongInfo("Cake By The Ocean", "DNCE", "2015", "Solo", "Just Dance 2017", "Cakebytheocean_cover_generic"));
        Chocolist.Add(new SongInfo("California Gurls", "Katy Perry", "2010", "Solo", "Just Dance 3", "Californiagurls"));
        Chocolist.Add(new SongInfo("Calypso", "Luis Fonsi & Stefflon Don", "2018", "Solo", "Just Dance 2019", "Calypso_cover_generic"));
        Chocolist.Add(new SongInfo("Can't Get Enough", "Becky G ft. Pitbull", "2013", "Solo", "Just Dance 2014", "Cantgetenoughdlc"));
        Chocolist.Add(new SongInfo("Can't Take My Eyes Off You", "Boys Town Gang", "1982", "Duet", "Just Dance 4", "Canttakemyeyes"));
        Chocolist.Add(new SongInfo("Can’t Feel My Face", "The Weeknd", "2015", "Solo", "Just Dance 2017", "Cantfeelmyface"));
        Chocolist.Add(new SongInfo("Carmen (Overture)", "Georges Bizet (The Just Dance Orchestra)", "1875", "Duet", "Just Dance 2018", "Carmen_cover_generic"));
        Chocolist.Add(new SongInfo("Carnaval Boom", "Latino Sunset", "2016", "Solo", "Just Dance 2017", "Samba"));
        Chocolist.Add(new SongInfo("Cercavo Amore", "Emma", "2012", "Solo", "Just Dance 4", "Amore"));
        Chocolist.Add(new SongInfo("Chantaje", "Shakira ft. Maluma", "2017", "Duet", "Just Dance 2018", "Chantaje_cover_generic"));
        Chocolist.Add(new SongInfo("Cheap Thrills", "Sia ft. Sean Paul", "2016", "Solo", "Just Dance 2017", "Cheapthrills"));
        Chocolist.Add(new SongInfo("Cheerleader (Felix Jaehn Remix)", "OMI", "2014", "Dance Crew", "Just Dance Unlimited", "Cheerleader_cover_generic"));
        Chocolist.Add(new SongInfo("Chiwawa", "Wanko Ni Mero Mero", "2015", "Solo", "Just Dance 2016", "Chiwawa_square_HD_Real"));
        Chocolist.Add(new SongInfo("Circus", "Britney Spears", "2008", "Dance Crew", "Just Dance 2016", "Circus"));
        Chocolist.Add(new SongInfo("Cola Song", "INNA ft. J Balvin", "2014", "Solo", "Just Dance 2017", "Colasong_cover_generic"));
        Chocolist.Add(new SongInfo("Cool for the Summer", "Demi Lovato", "2015", "Solo", "Just Dance 2016", "Cool_for_the_summer_HD_Square_Real"));
        Chocolist.Add(new SongInfo("Copacabana", "Barry Manilow (Frankie Bostello)", "1978", "Dance Crew", "Just Dance 2016", "Copacabana_Square_HD_Real"));
        Chocolist.Add(new SongInfo("Cosmic Girl", "Jamiroquai", "1996", "Solo", "Just Dance 2", "Cosmicgirl"));
        Chocolist.Add(new SongInfo("Cosmic Party", "Equinox Stars", "2018", "Solo", "Just Dance 2019 (Kids Mode)", "Spacegirlkids_cover_generic"));
        Chocolist.Add(new SongInfo("Cotton Eye Joe", "Rednex", "1994", "Solo", "Just Dance", "Cotton_jdnow_cover_generic_updated"));
        Chocolist.Add(new SongInfo("Crazy Christmas", "Santa Clones", "2010", "Solo", "Just Dance 2", "Xmascoach"));
        Chocolist.Add(new SongInfo("Crazy Little Thing Called Love ", "Queen", "1979", "Duet", "Just Dance 3", "Crazylittle_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Criminal", "Natti Natasha and Ozuna", "2017", "Duet", "Just Dance Unlimited", "Criminal_cover_generic"));
        Chocolist.Add(new SongInfo("Crucified", "Army of Lovers", "1991", "Dance Crew", "Just Dance 4", "Crucifiedquat"));
        Chocolist.Add(new SongInfo("Crying Blood", "V.V Brown", "2008", "Solo", "Just Dance 2", "Cryingblood-0"));
        Chocolist.Add(new SongInfo("Daddy Cool", "Boney M. (Groove Century)", "1976", "Solo", "Just Dance 2018", "Daddycool_cover_generic"));
        Chocolist.Add(new SongInfo("Dagomba", "Sorcerer", "2003", "Solo", "Just Dance 2", "Electrotribaldlc"));
        Chocolist.Add(new SongInfo("Dame Tu Cosita", "El Chombo Ft. Cutty Ranks", "2018", "Solo", "Just Dance Unlimited", "Dametu_cover_generic"));
        Chocolist.Add(new SongInfo("Dancing Queen", "ABBA", "1976", "Trio", "Just Dance Unlimited", "Dancingqueen_cover_generic"));
        Chocolist.Add(new SongInfo("Danse (Pop Version)", "Tal", "2013", "Solo", "Just Dance 2014", "Dansepopversion"));
        Chocolist.Add(new SongInfo("Despacito", "Luis Fonsi ft. Daddy Yankee", "2017", "Dance Crew", "Just Dance 2018", "Despacito"));
        Chocolist.Add(new SongInfo("Dharma", "Headhunterz & KSHMR", "2016", "Solo", "Just Dance 2018", "Dharma_cover_generic"));
        Chocolist.Add(new SongInfo("Die Young", "Ke$ha", "2012", "Duet", "Just Dance 4", "Dieyoungdlc"));
        Chocolist.Add(new SongInfo("Diggin' in the Dirt", "Stefanie Heinzmann", "2012", "Solo", "Just Dance 4", "Diggin"));
        Chocolist.Add(new SongInfo("Diggy", "Spencer Ludwig", "2016", "Solo", "Just Dance 2018", "Diggy_cover_generic"));
        Chocolist.Add(new SongInfo("Domino", "Jessie J", "2012", "Solo", "Just Dance 4", "Domino"));
        Chocolist.Add(new SongInfo("Don't You Worry Child", "Swedish House Mafia ft. John Martin", "2013", "Solo", "Just Dance 2014", "Dontyouworrydlc"));
        Chocolist.Add(new SongInfo("Done for Me", "Charlie Puth ft. Kehlani", "2018", "Duet", "Just Dance Unlimited", "Doneforme_cover_generic"));
        Chocolist.Add(new SongInfo("Don’t Let Me Down", "The Chainsmokers ft. Daya", "2016", "Duet", "Just Dance Unlimited", "DontLet_Cover_Generic"));
        Chocolist.Add(new SongInfo("Don’t Stop Me Now", "Queen", "1978", "Solo", "Just Dance 2017", "Dontstopme"));
        Chocolist.Add(new SongInfo("Don’t Wanna Know", "Maroon 5", "2016", "Solo", "Just Dance 2017", "RedMangoose_Cover_Generic"));
        Chocolist.Add(new SongInfo("Don’t Worry", "Madcon ft. Ray Dalton", "2015", "Duet", "Just Dance Unlimited", "DontWorryMadcon_Cover_Generic"));
        Chocolist.Add(new SongInfo("Don’t Worry Be Happy", "Bobby McFerrin (The Bench Men)", "1988", "Trio", "Just Dance 2015", "Dontworry"));
        Chocolist.Add(new SongInfo("Down By The Riverside", "The Reverend Horatio Duncan & Amos Sweets", "1927", "Solo", "Just Dance 2", "Riversidenow"));
        Chocolist.Add(new SongInfo("Dragostea Din Tei", "O-Zone", "2003", "Trio", "Just Dance 2017", "Dragosteadintei"));
        Chocolist.Add(new SongInfo("Drop the Mambo", "Diva Carmina", "2015", "Solo", "Just Dance 2016", "Drop_the_mambo_HD_Square_Real"));
        Chocolist.Add(new SongInfo("Dynamite", "Taio Cruz", "2010", "Dance Crew", "Just Dance 3", "Dynamitequat"));
        Chocolist.Add(new SongInfo("E.T.", "Katy Perry", "2010", "Solo", "Just Dance 3", "ET"));
        Chocolist.Add(new SongInfo("El Tiki", "Maluma", "2015", "Duet", "Just Dance 2017", "Eltiki"));
        Chocolist.Add(new SongInfo("Epic Sirtaki", "Cast of Zorba the Greek (The Bouzouki’s)", "2014", "Trio", "Just Dance 2015", "Sirtaki"));
        Chocolist.Add(new SongInfo("Error", "Natalia Nykiel", "2016", "Solo", "Just Dance Unlimited", "Error_cover_generic"));
        Chocolist.Add(new SongInfo("Eye of the Tiger", "Survivor", "1982", "Solo", "Just Dance", "Eyeofthetiger_jdnow"));
        Chocolist.Add(new SongInfo("Fame", "Irene Cara (The Girly Team)", "1980", "Solo", "Just Dance", "Fame_square"));
        Chocolist.Add(new SongInfo("Familiar", "Liam Payne ft. J.Balvin", "2018", "Solo", "Just Dance 2019", "Familiar_cover_generic"));
        Chocolist.Add(new SongInfo("Fancy", "Iggy Azalea ft. Charli XCX", "2014", "Trio", "Just Dance 2016", "Fancy"));
        Chocolist.Add(new SongInfo("Fearless Pirate", "Marine Band", "2016", "Solo", "Just Dance 2018 (Kids Mode)", "Fearlesspiratekids_cover_generic"));
        Chocolist.Add(new SongInfo("Feel It Still", "Portugal. The Man", "2017", "Solo", "Just Dance Unlimited", "Feelit_cover_generic"));
        Chocolist.Add(new SongInfo("Feel So Right", "Imposs ft. Konshens", "2013", "Solo", "Just Dance 2014", "Feel_so_right_jdn"));
        Chocolist.Add(new SongInfo("Fight Club", "Lights", "2017", "Solo", "Just Dance 2018", "Sidewinder_cover_generic"));
        Chocolist.Add(new SongInfo("Finesse (Remix)", "Bruno Mars ft. Cardi B", "2018", "Dance Crew", "Just Dance 2019", "Finesse_cover_generic"));
        Chocolist.Add(new SongInfo("Fire On The Floor", "Michelle Delamor", "2018", "Solo", "Just Dance 2019", "Fireonthedancefloor_cover_generic"));
        Chocolist.Add(new SongInfo("Firework", "Katy Perry", "2010", "Solo", "Just Dance 2", "Firework_2"));
        Chocolist.Add(new SongInfo("Flashdance ... What a Feeling", "Irene Cara (The Girly Team)", "1983", "Solo", "Just Dance 2014", "Whatafeeling"));
        Chocolist.Add(new SongInfo("Footloose", "Kenny Loggin (Top Culture)", "1984", "Solo", "Just Dance 2018", "Footloose"));
        Chocolist.Add(new SongInfo("Fun", "Pitbull ft. Chris Brown", "2014", "Solo", "Just Dance 2016", "Fun"));
        Chocolist.Add(new SongInfo("Funky Robot", "Dancing Bros.", "2017", "Solo", "Just Dance 2018 (Kids Mode)", "Funkyrobotkids_cover_generic"));
        Chocolist.Add(new SongInfo("Funkytown", "Lipps Inc. (Sweat Invaders)", "1980", "Solo", "Just Dance 2", "Funkytown_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Futebol Crazy", "The World Cup Girls", "2009", "Solo", "Just Dance 2", "Futebol"));
        Chocolist.Add(new SongInfo("Gangnam Style (강남스타일)", "PSY", "2012", "Duet", "Just Dance 4", "Gangnamstyledlc"));
        Chocolist.Add(new SongInfo("Gentleman", "PSY", "2013", "Solo", "Just Dance 2014", "Gentleman"));
        Chocolist.Add(new SongInfo("Get Ugly", "Jason Derulo", "2015", "Trio", "Just Dance Unlimited", "Getugly"));
        Chocolist.Add(new SongInfo("Ghost In The Keys", "Halloween Thrills", "2016", "Dance Crew", "Just Dance 2017", "Ghostinthekeys"));
        Chocolist.Add(new SongInfo("Ghostbusters", "Ray Parker, Jr.", "1984", "Dance Crew", "Just Dance 2014", "Ghostbusters"));
        Chocolist.Add(new SongInfo("Gibberish", "MAX", "2015", "Duet", "Just Dance 2016", "Gibberish_HD_Square_real"));
        Chocolist.Add(new SongInfo("Gimme! Gimme! Gimme! (A Man After Midnight)", "ABBA", "1979", "Solo", "Just Dance 2014", "Gimmegimme"));
        Chocolist.Add(new SongInfo("Girlfriend", "Avril Lavigne", "2007", "Duet", "Just Dance 2", "Girlfriendbigsquare"));
        Chocolist.Add(new SongInfo("Girls Just Want to Have Fun", "Cyndi Lauper", "1983", "Solo", "Just Dance", "Girlsjustwant_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Good Feeling", "Flo Rida", "2011", "Solo", "Just Dance 4", "Goodfeeling"));
        Chocolist.Add(new SongInfo("Got That", "Gigi Rowe", "2017", "Solo", "Just Dance 2018", "Gotthat_cover_generic"));
        Chocolist.Add(new SongInfo("Groove", "Jack & Jack", "2014", "Duet", "Just Dance 2017", "Groove_cover_generic"));
        Chocolist.Add(new SongInfo("Hala Bel Khamis", "Maan Barghouth", "2018", "Solo", "Just Dance 2019", "Halabel_cover_generic"));
        Chocolist.Add(new SongInfo("HandClap", "Fitz and The Tantrums", "2016", "Trio", "Just Dance Unlimited", "HandClap_Cover_Generic"));
        Chocolist.Add(new SongInfo("Hangover (BaBaBa)", "Buraka Som Sistema", "2011", "Duet", "Just Dance 2016", "Hangover_HD_SQUARE"));
        Chocolist.Add(new SongInfo("Happy", "Pharrell Williams", "2013", "Solo", "Just Dance 2015", "Happy"));
        Chocolist.Add(new SongInfo("Happy Farm", "Groove Century", "2016", "Solo", "Just Dance 2018 (Kids Mode)", "Happyfarmkids_cover_generic"));
        Chocolist.Add(new SongInfo("Havana", "Camila Cabello", "2017", "Solo", "Just Dance 2019", "Havana_cover_generic"));
        Chocolist.Add(new SongInfo("Heart of Glass", "Blondie", "1979", "Solo", "Just Dance", "Heartofglass"));
        Chocolist.Add(new SongInfo("Heartbeat Song", "Kelly Clarkson", "2015", "Solo", "Just Dance 2016", "Heartbeat"));
        Chocolist.Add(new SongInfo("Heavy Cross", "Gossip", "2009", "Solo", "Just Dance 4", "180px-Heavycross"));
        Chocolist.Add(new SongInfo("Hey Mama", "David Guetta ft. Nicki Minaj, Bebe Rexha, & Afrojack", "2014", "Trio", "Just Dance 2016", "Heymama"));
        Chocolist.Add(new SongInfo("Hey Ya ", "Outkast", "2003", "Solo", "Just Dance 2", "Heyya"));
        Chocolist.Add(new SongInfo("Hips Don’t Lie", "Shakira ft. Wyclef Jean", "2005", "Solo", "Just Dance 2017", "Hips"));
        Chocolist.Add(new SongInfo("Hit 'Em Up Style (Oops!)", "Blu Cantrell", "2001", "Solo", "Just Dance 4", "Hitemup"));
        Chocolist.Add(new SongInfo("Hit The Lights", "Selena Gomez & the Scene", "2012", "Solo", "Just Dance 4", "Hitthelights"));
        Chocolist.Add(new SongInfo("Hit The Road Jack", "Ray Charles (Charles Percy)", "1961", "Duet", "Just Dance 2016", "Hit_the_road_jack"));
        Chocolist.Add(new SongInfo("Hold My Hand", "Jess Glynne", "2015", "Solo", "Just Dance Unlimited", "Holdmyhand_cover_generic"));
        Chocolist.Add(new SongInfo("Holding Out for a Hero", "Bonnie Tyler", "1984", "Solo", "Just Dance 2015", "Holdingoutupdate"));
        Chocolist.Add(new SongInfo("Holiday", "Madonna (The Hit Crew)", "1982", "Solo", "Just Dance 2", "HolidayRemake"));
        Chocolist.Add(new SongInfo("Hot n Cold", "Katy Perry", "2008", "Solo", "Just Dance", "Hotncold_small"));
        Chocolist.Add(new SongInfo("Hot Stuff", "Donna Summer", "1980", "Duet", "Just Dance 2", "Hotstuff"));
        Chocolist.Add(new SongInfo("How Deep Is Your Love", "Calvin Harris and Disciples", "2015", "Solo", "Just Dance Unlimited", "HowDeep_Cover_Generic"));
        Chocolist.Add(new SongInfo("How Far I’ll Go", "Auli’i Cravalho", "2016", "Solo", "Just Dance 2018", "Howfar_cover_generic"));
        Chocolist.Add(new SongInfo("Hungarian Dance No. 5", "Johannes Brahms", "1880", "Duet", "Just Dance 3", "Hungariandance_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("I Feel Love", "Donna Summer", "1977", "Solo", "Just Dance 3", "Ifeellove_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("I Get Around", "The Beach Boys", "1966", "Solo", "Just Dance", "Getaround"));
        Chocolist.Add(new SongInfo("I Gotta Feeling", "The Black Eyed Peas", "2009", "Solo", "Just Dance 2016", "IGotAFeelingSqu"));
        Chocolist.Add(new SongInfo("I Kissed a Girl", "Katy Perry", "2008", "Solo", "Just Dance 2014", "Ikissed-0"));
        Chocolist.Add(new SongInfo("I Like It", "The Blackout Allstars", "1994", "Duet", "Just Dance 4", "Ilikeitlike_cover_generic"));
        Chocolist.Add(new SongInfo("I Love Rock ‘N’ Roll", "Joan Jett & The Blackhearts (Fast Forward Highway)", "1981", "Solo", "Just Dance 2017", "Iloverock"));
        Chocolist.Add(new SongInfo("I Need Your Love", "Calvin Harris feat. Ellie Goulding", "2012", "Solo", "Just Dance 2014", "Ineedyourlovedlcupdated"));
        Chocolist.Add(new SongInfo("I Want You Back", "The Jackson 5", "1971", "Solo", "Just Dance 2", "Iwantyouback"));
        Chocolist.Add(new SongInfo("I Was Made For Lovin' You", "Kiss", "1979", "Dance Crew", "Just Dance 3", "Iwasmadequat"));
        Chocolist.Add(new SongInfo("I Will Survive", "Gloria Gaynor", "1978", "Solo", "Just Dance 2014", "Iwillsurvive"));
        Chocolist.Add(new SongInfo("I'm Still Standing", "Elton John (Top Culture)", "1983", "Solo", "Just Dance 2019", "Imstillstanding_cover_generic"));
        Chocolist.Add(new SongInfo("Idealistic ", "Digitalism", "2007", "Solo", "Just Dance 2", "Idealistic"));
        Chocolist.Add(new SongInfo("Ievan Polkka", "Hatsune Miku", "2007", "Solo", "Just Dance 2016", "Levanpolkka"));
        Chocolist.Add(new SongInfo("Imya 505", "Vremya i Steklo", "2015", "Solo", "Just Dance Unlimited", "Imya505_Cover_Phone"));
        Chocolist.Add(new SongInfo("In the Hall of the Pixel King", "Dancing Bros", "2016", "Solo", "Just Dance 2018", "8bitretake_cover_generic"));
        Chocolist.Add(new SongInfo("India Waale", "From the movie Happy New Year", "2014", "Duet", "Exclusive Track", "Indiawaale"));
        Chocolist.Add(new SongInfo("Instruction", "Jax Jones ft. Demi Lovato and Stefflon Don", "2017", "Solo", "Just Dance 2018", "Instruction_cover_generic"));
        Chocolist.Add(new SongInfo("Into You", "Ariana Grande", "2016", "Solo", "Just Dance 2017", "Intoyou_cover_generic"));
        Chocolist.Add(new SongInfo("Irish Meadow Dance", "O'Callaghan's Orchestra", "2015", "Dance Crew", "Just Dance 2016", "Saintpatrick"));
        Chocolist.Add(new SongInfo("Irish Meadow Dance", "O’Callaghan’s Orchestra", "2015", "Duet", "Just Dance 2019 (Kids Mode)", "Saintpatrickkids_cover_generic"));
        Chocolist.Add(new SongInfo("Isidora ", "Bog Bog Orkestar", "2013", "Solo", "Just Dance 2014", "Zagreb"));
        Chocolist.Add(new SongInfo("Istanbul ", "They Might Be Giants", "1990", "Dance Crew", "Just Dance 4", "Istanbulquat"));
        Chocolist.Add(new SongInfo("It's You", "Duck Sauce", "2013", "Solo", "Just Dance 2014", "Itsyoujustdance2014"));
        Chocolist.Add(new SongInfo("Itsy Bitsy Teenie Weenie Yellow Polka Dot Bikini", "Brian Hyland (The Sunlight Shakers)", "1950", "Duet", "Just Dance 2018", "Itsybitsyretake_cover_generic"));
        Chocolist.Add(new SongInfo("It’s Raining Men", "The Weather Girls", "1983", "Solo", "Just Dance 2", "Itsrainingmen_jdu_cover_generic"));
        Chocolist.Add(new SongInfo("I’m An Albatraoz", "AronChupa", "2014", "Solo", "Just Dance 2016", "SquareAlbatraoz"));
        Chocolist.Add(new SongInfo("Jai Ho! (You Are My Destiny)", "A.R. Rahman featuring the Pussycat Dolls and Nicole Scherzinger", "2009", "Solo", "Just Dance 2", "Jaihoyouaremydestiny"));
        Chocolist.Add(new SongInfo("Jailhouse Rock", "Elvis Presley", "1957", "Dance Crew", "Just Dance 4", "Jailhousequat"));
        Chocolist.Add(new SongInfo("Jambo Mambo", "Olé Orquestra", "1997", "Duet", "Just Dance 3", "Jambomambo_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Je sais pas danser", "Natoo", "2016", "Solo", "Just Dance Unlimited", "Natoo"));
        Chocolist.Add(new SongInfo("Jingle Bells", "Santa Clones", "1857", "Duet", "Just Dance 2019 (Kids Mode)", "Merrychristmaskids_cover_generic"));
        Chocolist.Add(new SongInfo("John Wayne", "Lady Gaga", "2017", "Solo", "Just Dance 2018", "Johnw_cover_generic"));
        Chocolist.Add(new SongInfo("Juju On That Beat", "Zay Hilfigerrr & Zayion McCall", "2016", "Duet", "Just Dance Unlimited", "Juju_Cover_Generic"));
        Chocolist.Add(new SongInfo("Jump (For My Love) ", "The Pointer Sisters (Girls Aloud)", "2003", "Duet", "Just Dance 3", "Jumpga"));
        Chocolist.Add(new SongInfo("Junto A Ti", "Martina Stoessel & Lodovica Comello (Disney’s Violetta)", "2012", "Trio", "Just Dance 2016", "Junati"));
        Chocolist.Add(new SongInfo("Just A Gigolo", "Louis Prima", "1956", "Duet", "Just Dance 2014", "Gigolo"));
        Chocolist.Add(new SongInfo("Just Dance", "Lady Gaga feat. Colby O'Donis", "2008", "Solo", "Just Dance 2014", "Justdanceong"));
        Chocolist.Add(new SongInfo("J’suis pas jalouse", "Andy Raconte", "2017", "Duet", "Just Dance Unlimited", "Andy_cover_generic"));
        Chocolist.Add(new SongInfo("Kaboom Pow", "Nikki Yanofsky", "2014", "Solo", "Just Dance 2016", "Kaboompow"));
        Chocolist.Add(new SongInfo("Katti Kalandal", "Bollywood", "2000", "Duet", "Just Dance 2", "Kattikalandal"));
        Chocolist.Add(new SongInfo("Keep on Moving", "Michelle Delamor", "2017", "Solo", "Just Dance 2018", "Keepon_cover_generic"));
        Chocolist.Add(new SongInfo("Kissing Strangers", "DNCE ft. Nicki Minaj", "2017", "Duet", "Just Dance 2018", "Kissingstrangers_cover_generic"));
        Chocolist.Add(new SongInfo("Kool Kontact", "Glorious Black Belts", "2015", "Duet", "Just Dance 2016", "Kungfunk"));
        Chocolist.Add(new SongInfo("Kung Fu Fighting ", "Carl Douglass", "1974", "Duet", "Just Dance 2", "Kungfu_now"));
        Chocolist.Add(new SongInfo("Kurio ko uddah le jana ", "Bollywood Rainbow", "1979", "Duet", "Just Dance 3", "Kurio"));
        Chocolist.Add(new SongInfo("La Bicicleta", "Carlos Vives & Shakira", "2016", "Duet", "Just Dance 2017", "Bicicleta_cover_generic"));
        Chocolist.Add(new SongInfo("Land Of 1000 Dances", "Wilson Pickett", "1966", "Solo", "Just Dance 3", "Athousanddances"));
        Chocolist.Add(new SongInfo("Last Christmas", "Wham! (Santa Clones)", "1986", "Duet", "Just Dance 2017", "Lastchristmas"));
        Chocolist.Add(new SongInfo("Le Freak", "Chic", "1978", "Solo", "Just Dance", "Lefreak"));
        Chocolist.Add(new SongInfo("Lean On", "Major Lazer & DJ Snake ft. MØ", "2015", "Dance Crew", "Just Dance 2017", "Leanon"));
        Chocolist.Add(new SongInfo("Leg Song", "LULU", "2016", "Solo", "2017", "Legsongchn_cover_generic"));
        Chocolist.Add(new SongInfo("Leila", "Cheb Salama", "2016", "Solo", "Just Dance 2017", "Leila"));
        Chocolist.Add(new SongInfo("Let It Go", "Idina Menzel (Disney's Frozen)", "2013", "Duet", "Just Dance 2015", "Letitgo_cover_generic"));
        Chocolist.Add(new SongInfo("Let Me Love You", "DJ Snake ft. Justin Bieber", "2016", "Duet", "Just Dance 2017 (Ubisoft Club)", "Blackmamba_cover_generic"));
        Chocolist.Add(new SongInfo("Let’s Groove", "Earth, Wind & Fire (Equinox Stars)", "1981", "Trio", "Just Dance 2016", "Letsgroove"));
        Chocolist.Add(new SongInfo("Lights", "Ellie Goulding", "2011", "Solo", "Just Dance 2016", "Lights"));
        Chocolist.Add(new SongInfo("Like I Would", "ZAYN", "2016", "Solo", "Just Dance 2017", "Likeiwould"));
        Chocolist.Add(new SongInfo("Little Swing", "AronChupa ft. Little Sis Nora", "2016", "Duet", "Just Dance 2017", "Littleswing"));
        Chocolist.Add(new SongInfo("Lollipop ", "MIKA", "2007", "Solo", "Just Dance 3", "Lollipop"));
        Chocolist.Add(new SongInfo("Love Boat", "Jack Jones (Frankie Bostello)", "1979", "Solo", "Just Dance 2014", "Loveboat"));
        Chocolist.Add(new SongInfo("Love Is All", "Roger Glover and The Butterfly Ball (The Sunlight Shakers)", "1974", "Duet", "Just Dance 2015", "Loveisall"));
        Chocolist.Add(new SongInfo("Love Ward", "Hatsune Miku", "2009", "Trio", "Just Dance 2018", "Loveward_cover_generic"));
        Chocolist.Add(new SongInfo("Love You Like A Love Song", "Selena Gomez & The Scene", "2011", "Solo", "Just Dance 4", "Loveyoulike_cover_generic"));
        Chocolist.Add(new SongInfo("Lush Life", "Zara Larsson", "2015", "Solo", "Just Dance Unlimited", "Lush_cover_generic"));
        Chocolist.Add(new SongInfo("Macarena", "Los Del Rio (The Girly Team)", "1995", "Dance Crew", "Just Dance 2015", "Macarena_cover_generic"));
        Chocolist.Add(new SongInfo("Magic Halloween", "Halloween Thrills", "2017", "Duet", "Just Dance 2018 (Kids Mode)", "Magichalloweenkids_cover_generic"));
        Chocolist.Add(new SongInfo("Make It Jingle", "Big Freedia", "2017", "Solo", "Just Dance 2018", "Makeitjingle_cover_generic"));
        Chocolist.Add(new SongInfo("Make Me Feel", "Janelle Monáe", "2018", "Solo", "Just Dance 2019", "Makemefeel_cover_generic"));
        Chocolist.Add(new SongInfo("Mamasita", "Latino Sunset", "2001", "Duet", "Just Dance 3", "Mamasita"));
        Chocolist.Add(new SongInfo("Mambo No. 5 (A Little Bit of Monika)", "Lou Bega (The Lemon Cubes)", "1999", "Duet", "Just Dance 2", "Mambo5big"));
        Chocolist.Add(new SongInfo("Maneater", "Nelly Furtado", "2006", "Solo", "Just Dance 4", "Maneater-0"));
        Chocolist.Add(new SongInfo("Maps", "Maroon 5", "2014", "Solo", "Just Dance 2015", "Mad"));
        Chocolist.Add(new SongInfo("Mashed Potato Time", "Dee Dee Sharp", "1962", "Solo", "Just Dance", "Potato"));
        Chocolist.Add(new SongInfo("Me Too", "Meghan Trainor", "2016", "Solo", "Just Dance Unlimited", "MeToo_Cover_Generic"));
        Chocolist.Add(new SongInfo("Medicina", "Anitta", "2018", "Dance Crew", "Just Dance Unlimited", "Medicina_Cover_Generic"));
        Chocolist.Add(new SongInfo("Mi Gente", "J Balvin & Willy William", "2017", "Trio", "Just Dance Unlimited", "Migente_cover_generic"));
        Chocolist.Add(new SongInfo("Miss Understood", "Sammie", "2013", "Solo", "Just Dance 2014", "Misunderstood"));
        Chocolist.Add(new SongInfo("Monster Mash", "Boris Pickett & The Crypt-Kickers (The Frighteners)", "1962", "Solo", "Just Dance 2", "Monstermash"));
        Chocolist.Add(new SongInfo("Monsters of Jazz", "Glove Century", "2017", "Solo", "Just Dance 2019 (Kids Mode)", "Monstersacademykids_cover_generic"));
        Chocolist.Add(new SongInfo("Moskau", "Dschinghis Khan (Dancing Bros.)", "1979", "Duet", "Just Dance 2014", "Moskau"));
        Chocolist.Add(new SongInfo("Move Your Feet ", "Junior Senior", "2003", "Solo", "Just Dance 2", "Moveyourfeet_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Movement is Happiness (Find Your Thing)", "Avishay Goren & Yossi Cohen", "2014", "Solo", "Exclusive Track", "Movement_is_happiness_find_your_thing_jdn"));
        Chocolist.Add(new SongInfo("Moves Like Jagger", "Maroon 5 ft. Christina Aguilera", "2011", "Solo", "Just Dance 4", "Moveslikedlc"));
        Chocolist.Add(new SongInfo("Mr. Saxobeat", "Alexandra Stan", "2011", "Solo", "Just Dance 4", "Mrsaxobeat"));
        Chocolist.Add(new SongInfo("Mugsy Baloney", "Charleston", "1924", "Duet", "Just Dance 2", "Mugsybaloney"));
        Chocolist.Add(new SongInfo("My Main Girl", "MainStreet", "2013", "Solo", "Just Dance 2014", "Maingirldlc"));
        Chocolist.Add(new SongInfo("Naughty Girl", "Beyoncé", "2003", "Solo", "Just Dance 2018", "Naughtygirl_cover_generic"));
        Chocolist.Add(new SongInfo("Never Can Say Goodbye", "Gloria Gaynor", "1974", "Solo", "Just Dance 2015", "Nevercansay"));
        Chocolist.Add(new SongInfo("New World", "Krewella & Yellow Claw ft. Vava", "2017", "Solo", "Just Dance 2019", "Newworld_cover_generic"));
        Chocolist.Add(new SongInfo("Nine In The Afternoon", "Panic! At the Disco", "2008", "Duet", "Just Dance 2", "Nineafternoon_now"));
        Chocolist.Add(new SongInfo("Nitro Bot", "Sentai Express", "2013", "Duet", "Just Dance 2014", "Robotrock"));
        Chocolist.Add(new SongInfo("No Control", "One Direction", "2014", "Dance Crew", "Just Dance 2016", "Nocontrol"));
        Chocolist.Add(new SongInfo("No Lie", "Sean Paul ft. Dua Lipa", "2017", "Duet", "Just Dance Unlimited", "Nolie_cover_generic"));
        Chocolist.Add(new SongInfo("No Limit", "2 Unlimited", "1993", "Duet", "Just Dance 3", "Nolimit"));
        Chocolist.Add(new SongInfo("Oath", "Cher Lloyd ft. Becky G", "2012", "Duet", "Just Dance 4", "Oath"));
        Chocolist.Add(new SongInfo("Obsesión", "Aventura", "2002", "Duet", "Just Dance 2019", "Obsessionretake_cover_generic"));
        Chocolist.Add(new SongInfo("Oh No!", "Marina and the Diamonds", "2010", "Solo", "Just Dance 4", "Ohno"));
        Chocolist.Add(new SongInfo("Oishii Oishii", "Wanko Ni Mero Mero", "2016", "Duet", "Just Dance 2017", "Oishii"));
        Chocolist.Add(new SongInfo("On Ne Porte Pas De Sous-Vêtements", "McFly & Carlito", "2018", "Duet", "Just Dance 2019", "Onneportepas_cover_generic"));
        Chocolist.Add(new SongInfo("Ona tańczy dla mnie", "Weekend", "2012", "Duet", "Just Dance Unlimited", "OnaTanczyDlaMnie_Cover_Phone"));
        Chocolist.Add(new SongInfo("One Kiss", "Calvin Harris, Dua Lipa", "2018", "Solo", "Just Dance 2019", "Onekiss_cover_generic"));
        Chocolist.Add(new SongInfo("One Way Or Another (Teenage Kicks)", "One Direction", "2013", "Solo", "Just Dance 2014", "Onewaydlcupdated"));
        Chocolist.Add(new SongInfo("Oops!...I Did It Again", "Britney Spears (The Girly Team)", "2000", "Dance Crew", "Just Dance 4", "Ididitagainquat"));
        Chocolist.Add(new SongInfo("Pac-Man", "Toshio Kai (Dancing Bros.)", "1980", "Dance Crew", "Just Dance 2019", "Pacman_cover_generic"));
        Chocolist.Add(new SongInfo("Part Of Me", "Katy Perry", "2012", "Solo", "Just Dance 4", "PartOfMe"));
        Chocolist.Add(new SongInfo("Party Rock Anthem", "LMFAO ft. Lauren Bennett & GoonRock", "2011", "Solo", "Just Dance 3", "Partyrock"));
        Chocolist.Add(new SongInfo("Pixie Land", "The Sunlight Shakers", "2017", "Solo", "Just Dance 2018 (Kids Mode)", "Pixielandkids_cover_generic"));
        Chocolist.Add(new SongInfo("PoPiPo", "Hatsune Miku", "2008", "Trio", "Just Dance 2017", "Popipo_cover_generic"));
        Chocolist.Add(new SongInfo("Pound The Alarm", "Nicki Minaj", "2012", "Dance Crew", "Just Dance 2014", "Poundthealarm"));
        Chocolist.Add(new SongInfo("Primadonna", "Marina and the Diamonds", "2012", "Solo", "Just Dance 4", "Primadonna"));
        Chocolist.Add(new SongInfo("Prince Ali", "Disney's Aladdin", "1992", "Dance Crew", "Just Dance 2014", "Princeali_cover_generic"));
        Chocolist.Add(new SongInfo("Professor Pumplestickle", "Nick Phoenix and Thomas J. Bergersen", "2006", "Duet", "Just Dance 2", "Professeurdlc"));
        Chocolist.Add(new SongInfo("Promiscuous", "Nelly Furtado ft. Timbaland", "2006", "Duet", "Just Dance 3", "Promiscuous_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Qia La Yong Yuan OK - Future Underworld Mix", "Alan Tam", "1990", "Solo", "2017", "Karaokeforeverchn_cover_generic"));
        Chocolist.Add(new SongInfo("Rabiosa", "Shakira ft. El Cata", "2010", "Solo", "Just Dance 2016", "Rabiosa"));
        Chocolist.Add(new SongInfo("RADICAL", "Dyro & Dannic", "2014", "Solo", "Just Dance 2017", "Radical"));
        Chocolist.Add(new SongInfo("Rasputin", "Boney M.", "1978", "Solo", "Just Dance 2", "Rasputin"));
        Chocolist.Add(new SongInfo("Risky Business", "Jorge Blanco", "2017", "Solo", "Just Dance 2018", "Riskybusiness_cover_generic"));
        Chocolist.Add(new SongInfo("Roar", "Katy Perry", "2013", "Solo", "Just Dance 2014", "Kilopapadlc-0"));
        Chocolist.Add(new SongInfo("Rock n Roll", "Avril Lavigne", "2013", "Solo", "Just Dance 2014", "Rocknrolldlc2014"));
        Chocolist.Add(new SongInfo("Rock n' Roll (Will Take You to the Mountain)", "Skrillex", "2010", "Solo", "Just Dance 4", "Rocknroll_cover_generic"));
        Chocolist.Add(new SongInfo("Rockabye", "Clean Bandit ft. Sean Paul and Anne-Marie", "2016", "Duet", "Just Dance 2018", "Rockabye"));
        Chocolist.Add(new SongInfo("Rockafeller Skank", "Fatboy Slim", "1998", "Solo", "Just Dance 2", "Rockafeller_cover_generic"));
        Chocolist.Add(new SongInfo("Run the Night", "Gigi Rowe", "2016", "Solo", "Just Dance 2017", "Runthenight_cover_generic"));
        Chocolist.Add(new SongInfo("Safe And Sound", "Capital Cities", "2011", "Solo", "Just Dance 2014", "Safeandsound_cover_generic"));
        Chocolist.Add(new SongInfo("Sax", "Fleur East", "2015", "Trio", "Just Dance Unlimited", "Sax_Cover_Phone"));
        Chocolist.Add(new SongInfo("Sayonara", "Wanko Ni Mero Mero", "2017", "Solo", "Just Dance 2018", "Sayonararetake_cover_generic"));
        Chocolist.Add(new SongInfo("September", "Earth, Wind & Fire (Equinox Stars)", "1978", "Trio", "Just Dance 2017", "September_jdn"));
        Chocolist.Add(new SongInfo("Sexy And I Know It ", "LMFAO", "2011", "Solo", "Just Dance 2014", "Sexyandiknowitdlc"));
        Chocolist.Add(new SongInfo("Shaky Shaky", "Daddy Yankee", "2015", "Solo", "Just Dance 2019", "Shaky_cover_generic"));
        Chocolist.Add(new SongInfo("Shape of You", "Ed Sheeran", "2017", "Solo", "Just Dance 2018", "Shapeofyou_cover_generic"));
        Chocolist.Add(new SongInfo("She’s Got Me Dancing", "Tommy Sparks", "2009", "Solo", "Just Dance 3", "Gotmedancing"));
        Chocolist.Add(new SongInfo("Shut Up and Dance", "Walk the Moon", "2014", "Duet", "Just Dance Unlimited", "Shutup_jdn"));
        Chocolist.Add(new SongInfo("Side to Side", "Ariana Grande ft. Nicki Minaj", "2016", "Solo", "Just Dance 2018", "Sideto_cover_generic"));
        Chocolist.Add(new SongInfo("Single Ladies (Put a Ring on It)", "Beyoncé", "2008", "Solo", "Just Dance 2017", "Singleladies_cover_generic"));
        Chocolist.Add(new SongInfo("Slumber Party", "Britney Spears ft. Tinashe", "2016", "Dance Crew", "Just Dance 2018", "Slumberparty_cover_generic"));
        Chocolist.Add(new SongInfo("Smile", "IOWA", "2013", "Solo", "Just Dance 2016", "Ulibayssia"));
        Chocolist.Add(new SongInfo("So Glamorous", "The Girly Team", "2012", "Solo", "Just Dance 4", "Glamorouscusto"));
        Chocolist.Add(new SongInfo("Somethin’ Stupid", "Robbie Williams and Nicole Kidman", "2001", "Duet", "Just Dance 3", "Somethinstupid"));
        Chocolist.Add(new SongInfo("Sorry", "Justin Bieber", "2015", "Solo", "Just Dance 2017", "Sorry"));
        Chocolist.Add(new SongInfo("Soul Searchin’", "Groove Century", "1999", "Solo", "Just Dance 3", "Soulsearch"));
        Chocolist.Add(new SongInfo("Spectronizer", "Sentai Express", "2009", "Dance Crew", "Just Dance 3", "Spectronizerquat"));
        Chocolist.Add(new SongInfo("Stadium Flow", "Imposs", "2015", "Solo", "Just Dance 2016", "Stadium_flow"));
        Chocolist.Add(new SongInfo("Starships", "Nicki Minaj", "2012", "Solo", "Just Dance 2014", "Starships_JDNOW"));
        Chocolist.Add(new SongInfo("Step by Step", "New Kids on the Block", "1990", "Solo", "Just Dance", "Step_by_step_jdn"));
        Chocolist.Add(new SongInfo("Stuck On A Feeling", "Prince Royce", "2014", "Solo", "Just Dance 2016", "StuckOnAFeeling"));
        Chocolist.Add(new SongInfo("Sugar Dance", "The Just Dance Band", "2017", "Solo", "Just Dance 2018", "Sugardance_cover_generic"));
        Chocolist.Add(new SongInfo("Summer", "Calvin Harris", "2014", "Solo", "Just Dance 2015", "Summer_cover_generic"));
        Chocolist.Add(new SongInfo("Sun", "DEMO", "1999", "Solo", "Just Dance Unlimited", "Sun_cover_generic"));
        Chocolist.Add(new SongInfo("Super Bass", "Nicki Minaj", "2011", "Solo", "Just Dance 4", "Superbass"));
        Chocolist.Add(new SongInfo("Superstition", "Stevie Wonder", "1972", "Solo", "Just Dance 4", "Superstitionjustdance4"));
        Chocolist.Add(new SongInfo("Sway (Quién Será)", "Michael Bublé (Marine Band)", "2003", "Duet", "Just Dance 2", "Swayjdnow"));
        Chocolist.Add(new SongInfo("Sweet Little Unforgettable Thing", "Bea Miller", "2018", "Solo", "Just Dance 2019", "Sweetlittle_cover_generic"));
        Chocolist.Add(new SongInfo("Swish Swish", "Katy Perry ft. Nicki Minaj", "2017", "Dance Crew", "Just Dance 2018", "Swishswish_cover_generic"));
        Chocolist.Add(new SongInfo("Take Me Out", "Franz Ferdinand", "2003", "Solo", "Just Dance 2", "Takemeout_remake"));
        Chocolist.Add(new SongInfo("Take On Me", "a-ha", "1985", "Solo", "Just Dance 3", "Takeonme_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Taste The Feeling", "Avicii ft. Conrad Sewell", "2016", "Solo", "Just Dance Unlimited", "Tastethefeeling_updated"));
        Chocolist.Add(new SongInfo("Te Dominar", "Daya Luz", "2016", "Trio", "Just Dance 2017", "Tedominar"));
        Chocolist.Add(new SongInfo("Teacher", "Nick Jonas", "2014", "Solo", "Just Dance 2016", "Teacher"));
        Chocolist.Add(new SongInfo("Teenage Dream", "Katy Perry", "2010", "Solo", "Just Dance 3", "Teenagedream"));
        Chocolist.Add(new SongInfo("That's Not My Name ", "The Ting Tings", "2008", "Solo", "Just Dance 2", "ThatsNotMyName_JDU_Cover_Generic"));
        Chocolist.Add(new SongInfo("That's The Way (I Like It)", "KC and the Sunshine Band", "1975", "Solo", "Just Dance", "Thatstheway_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("The Choice Is Yours", "Darlus Dante Dijk", "2015", "Solo", "Exclusive Track", "Thechoice"));
        Chocolist.Add(new SongInfo("The Final Countdown", "Europe", "1986", "Duet", "Just Dance 4", "Thefinalcountdown"));
        Chocolist.Add(new SongInfo("The Greatest", "Sia", "2016", "Solo", "Just Dance Unlimited", "TheGreatest_Cover_Generic"));
        Chocolist.Add(new SongInfo("The Master Blaster", "Inspector Mareau", "1969", "Duet", "Just Dance 3", "Masterblaster"));
        Chocolist.Add(new SongInfo("The Other Side", "Jason Derulo", "2013", "Solo", "Just Dance 2014", "Otherside"));
        Chocolist.Add(new SongInfo("The Way", "Ariana Grande ft. Mac Miller", "2013", "Duet", "Just Dance 2014", "Theway"));
        Chocolist.Add(new SongInfo("The Way I Are (Dance With Somebody)", "Bebe Rexha ft. Lil Wayne", "2017", "Duet", "Just Dance 2018", "Cottonmouth_cover_generic"));
        Chocolist.Add(new SongInfo("The World is Ours", "David Correy ft. Monobloco", "2014", "Solo", "Just Dance 2014", "Theworlddlc_updated_jdn_square"));
        Chocolist.Add(new SongInfo("There Is Nothing Better In The World", "Bremenskiye Muzykanty", "1969", "Dance Crew", "Just Dance 2019", "Bremen_cover_online"));
        Chocolist.Add(new SongInfo("These Boots Are Made For Walking", "Nancy Sinatra (The Girly Team)", "1966", "Solo", "Just Dance 2016", "Theseboots"));
        Chocolist.Add(new SongInfo("This is Halloween", "Danny Elfman", "1993", "Dance Crew", "Just Dance 3", "Halloweenquat_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("This Is How We Do", "Katy Perry", "2013", "Dance Crew", "Just Dance 2016", "Thisishow"));
        Chocolist.Add(new SongInfo("Thumbs", "Sabrina Carpenter", "2016", "Solo", "Just Dance 2018 (Ubisoft Club)", "Thumbs_cover_generic"));
        Chocolist.Add(new SongInfo("Tico-Tico No Fubá", "Zequinha de Abreu (The Frankie Bostello Orchestra)", "1917", "Duet", "Just Dance 2017", "Ticotico"));
        Chocolist.Add(new SongInfo("TiK ToK ", "Ke$ha", "2009", "Solo", "Just Dance 2", "Tiktok"));
        Chocolist.Add(new SongInfo("Till I Find You", "Austin Mahone", "2014", "Solo", "Just Dance 2015", "Findyou"));
        Chocolist.Add(new SongInfo("Time Warp", "The Rocky Horror Picture Show (Halloween Thrills)", "1975", "Dance Crew", "Just Dance 4", "Timewarpquat"));
        Chocolist.Add(new SongInfo("Titanium", "David Guetta ft. Sia", "2011", "Solo", "Just Dance 2017", "Titanium"));
        Chocolist.Add(new SongInfo("Tribal Dance", "2 Unlimited", "1993", "Duet", "Just Dance 4", "Tribaldance"));
        Chocolist.Add(new SongInfo("Tumbum", "Yeni Alade", "2016", "Dance Crew", "Just Dance 2018", "Tumbum_cover_generic"));
        Chocolist.Add(new SongInfo("Turn Up The Love", "Far East Movement feat. Cover Drive", "2012", "Duet", "Just Dance 2014", "Turnupthelove"));
        Chocolist.Add(new SongInfo("Twist and Shake It", "The Girly Team", "2008", "Duet", "Just Dance 3", "Twistshakeit"));
        Chocolist.Add(new SongInfo("U Can't Touch This", "MC Hammer (Groove Century)", "1990", "Solo", "Just Dance", "Canttouchthis_"));
        Chocolist.Add(new SongInfo("Under the Sea", "Samuel E. Wright (Disney’s The Little Mermaid)", "1989", "Solo", "Just Dance 2016", "Under_the_sea"));
        Chocolist.Add(new SongInfo("Uptown Funk", "Mark Ronson ft. Bruno Mars", "2014", "Solo", "Just Dance 2016", "Uptownfunk"));
        Chocolist.Add(new SongInfo("Waka Waka (This Time for Africa)", "Shakira", "2010", "Trio", "Just Dance 2018", "Wakawaka_cover_generic"));
        Chocolist.Add(new SongInfo("Wake Me Up", "Avicii", "2013", "Solo", "Just Dance 2014", "Wakemeupdlc"));
        Chocolist.Add(new SongInfo("Wake Me Up Before You Go-Go", "Wham!", "1985", "Solo", "Just Dance 2", "Wakemeup_now"));
        Chocolist.Add(new SongInfo("Waking Up in Vegas", "Katy Perry", "2009", "Solo", "Just Dance 2014", "Wakingup"));
        Chocolist.Add(new SongInfo("Walk Like an Egyptian", "The Bangles", "1986", "Solo", "Just Dance 2", "Walklike_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Walk This Way", "Run DMC and Aerosmith", "1986", "Dance Crew", "Just Dance 2015", "Walkthisway"));
        Chocolist.Add(new SongInfo("Want To Want Me", "Jason Derulo", "2015", "Solo", "Just Dance 2016", "Want_me_to_me"));
        Chocolist.Add(new SongInfo("Want U Back", "Cher Lloyd ft. Astro", "2012", "Solo", "Just Dance 4", "Wantuback"));
        Chocolist.Add(new SongInfo("Watch Me (Whip/Nae Nae)", "Silentó", "2015", "Dance Crew", "Just Dance 2017", "Naenae"));
        Chocolist.Add(new SongInfo("We No Speak Americano ", "Yolanda Be Cool and DCUP (Hit the Electro Beat)", "2010", "Solo", "Just Dance 4", "Americano"));
        Chocolist.Add(new SongInfo("We R Who We R", "Ke$ha", "2010", "Solo", "Just Dance 4", "Werwhowerdlc"));
        Chocolist.Add(new SongInfo("What About Love ", "Austin Mahone", "2013", "Solo", "Just Dance 2014", "Whataboutlovedlc"));
        Chocolist.Add(new SongInfo("What Is Love", "Haddaway(Ultraclub 90)", "1993", "Solo", "Just Dance 2017", "Whatislove_cover_generic"));
        Chocolist.Add(new SongInfo("What Lovers Do", "Maroon 5 ft. SZA", "2017", "Duet", "Just Dance Unlimited", "Whatloversdo_cover_generic"));
        Chocolist.Add(new SongInfo("When The Rain Begins To Fall", "Jermaine Jackson and Pia Zadora (Sky Trucking)", "1984", "Duet", "Just Dance 2016", "When_the_rain"));
        Chocolist.Add(new SongInfo("Wherever I Go", "OneRepublic", "2016", "Solo", "Just Dance 2017", "Whereverigo"));
        Chocolist.Add(new SongInfo("Who Let the Dogs Out?", "Baha Men (The Sunlight Shakers)", "2000", "Solo", "Just Dance", "Dogsout"));
        Chocolist.Add(new SongInfo("Wild", "Jessie J ft. Big Sean", "2013", "Solo", "Just Dance 2014", "Wildjustdance2014"));
        Chocolist.Add(new SongInfo("William Tell Overture", "Rossini", "1829", "Duet", "Just Dance 2016", "Williamtell"));
        Chocolist.Add(new SongInfo("Worth It", "Fifth Harmony ft. Kid Ink", "2015", "Solo", "Just Dance 2017", "Worthit"));
        Chocolist.Add(new SongInfo("XMas Tree", "Bollywood Santa", "2014", "Duet", "Just Dance 2015", "Bollywoodxmas"));
        Chocolist.Add(new SongInfo("Y.M.C.A.", "Village People", "1978", "Dance Crew", "Just Dance 2014", "Ymca"));
        Chocolist.Add(new SongInfo("You Can't Hurry Love ", "The Supremes", "1966", "Duet", "Just Dance 2", "Canthurrylove"));
        Chocolist.Add(new SongInfo("You Make Me Feel...", "Cobra Starship feat. Sabi", "2011", "Solo", "Just Dance 4", "Youmakemefeeldlc"));
        Chocolist.Add(new SongInfo("You Never Can Tell", "Chuck Berry (A. Caveman & The Backseats)", "1963", "Duet", "Just Dance 2016", "Younevercan_jd2016_cover_generic"));
        Chocolist.Add(new SongInfo("You Spin Me Round (Like a Record)", "Dead or Alive", "1985", "Solo", "Just Dance 2015", "SpinMeRoundNew"));
        Chocolist.Add(new SongInfo("You're On My Mind", "Imposs ft. J.Perry", "2014", "Dance Crew Mash-Up", "Just Dance 2015", "Onmymind"));
        Chocolist.Add(new SongInfo("You're the First, the Last, My Everything ", "Barry White", "1974", "Dance Crew", "Just Dance 4", "You're_the_first_the_last_my_everything_jdn"));
        Chocolist.Add(new SongInfo("YOUTH", "Troye Sivan", "2015", "Solo", "Just Dance Unlimited", "Youth_Cover_Generic"));
        Chocolist.Add(new SongInfo("You’re The One That I Want", "John Travolta & Olivia Newton-John (From the movie Grease)", "1978", "Duet", "Just Dance 2016", "Youre_the_one"));
        Chocolist.Add(new SongInfo("Can’t Take My Eyes Off You ALT", "Boys Town Gang", "1982", "Wrestler/Alternate", "Just Dance 4", "Canttakemyeyesalt"));
        Chocolist.Add(new SongInfo("Good Feeling ALT", "Flo Rida", "2012", "Extreme", "Just Dance 4", "Goodfeelingalt"));
        Chocolist.Add(new SongInfo("Jailhouse Rock ALT", "Elvis Presley", "1957", "Line Dance", "Just Dance 4", "Jailhousealt"));
        Chocolist.Add(new SongInfo("Tribal Dance ALT", "2 Unlimited", "1993", "With A Katana", "Just Dance 4", "Tribaldancealt"));
        Chocolist.Add(new SongInfo("#thatPOWER ALT", "will.i.am ft. Justin Bieber", "2013", "Extreme", "Just Dance 2014", "Thatpoweralt_cover_generic"));
        Chocolist.Add(new SongInfo("#thatPOWER Stage", "will.i.am ft. Justin Bieber", "2013", "Sing Along/On-Stage", "Just Dance 2014", "Thatpoweroscdlc"));
        Chocolist.Add(new SongInfo("Blurred Lines ALT", "Robin Thicke ft. Pharrell Williams", "2013", "Extreme", "Just Dance 2014", "Blurredlinesaltdlc"));
        Chocolist.Add(new SongInfo("Gentleman ALT", "PSY", "2013", "Sweat", "Just Dance 2014", "Gentlemanswt"));
        Chocolist.Add(new SongInfo("Ghostbusters ALT", "Ray Parker, Jr.", "1984", "Sweat", "Just Dance 2014", "Ghostbustersswt_cover_generic"));
        Chocolist.Add(new SongInfo("Gimme! Gimme! Gimme! (A Man After Midnight) ALT", "ABBA", "1979", "Sing Along/On-Stage", "Just Dance 2014", "Gimmegimmeosc_jdu_cover_generic"));
        Chocolist.Add(new SongInfo("I Kissed a Girl ALT", "Katy Perry", "2009", "Sweat", "Just Dance 2014", "Ikissedswt"));
        Chocolist.Add(new SongInfo("I Kissed a Girl Stage", "Katy Perry", "2009", "Sing Along/On-Stage", "Just Dance 2014", "Ikissedosc"));
        Chocolist.Add(new SongInfo("I Will Survive ALT", "Gloria Gaynor", "1978", "Sing Along", "Just Dance 2014", "Iwillsurviveosc"));
        Chocolist.Add(new SongInfo("It’s You ALT", "Duck Sauce", "2013", "Sweat", "Just Dance 2014", "Itsyouswt_jdu_cover_generic"));
        Chocolist.Add(new SongInfo("Just Dance 2014", "Lady Gaga feat. Colby O'Donis", "2008", "Sweat", "Just Dance 2014", "Justdanceswtdlcupdated"));
        Chocolist.Add(new SongInfo("Just Dance On-Stage", "Lady Gaga feat. Colby O'Donis", "2008", "Sing Along/On-Stage", "Just Dance 2014", "Justdanceosc"));
        Chocolist.Add(new SongInfo("Pound The Alarm ALT", "Nicki Minaj", "2012", "Extreme", "Just Dance 2014", "Poundthealarmaltdlc"));
        Chocolist.Add(new SongInfo("Turn Up the Love ALT", "Far East Movement ft. Cover Drive", "2012", "Sumo", "Just Dance 2014", "Turnupthelovealt"));
        Chocolist.Add(new SongInfo("Happy ALT", "Pharrell Williams", "2013", "Sing Along", "Just Dance 2015", "Happyalt"));
        Chocolist.Add(new SongInfo("Let It Go ALT", "Idina Menzel (Disney's Frozen)", "2013", "Sing Along", "Just Dance 2015", "Letitgodlc_cover_generic"));
        Chocolist.Add(new SongInfo("Summer ALT", "Calvin Harris", "2014", "Fitness Dance/Sweat", "Just Dance 2015", "Summeralt"));
        Chocolist.Add(new SongInfo("Walk This Way ALT", "Run DMC & Aerosmith", "1986", "Old School/Extreme", "Just Dance 2015", "Walkthiswayaltupdate"));
        Chocolist.Add(new SongInfo("Taste The Feeling ALT", "Avicii ft. Conrad Sewell", "2016", "Alternate", "Just Dance Now", "Tastethefeelingalt"));
        Chocolist.Add(new SongInfo("Blurred Lines ALT", "Robin Thicke ft. Pharrell Williams", "2013", "Fanmade", "Just Dance Now", "Justmaxbl"));
        Chocolist.Add(new SongInfo("HandClap ALT", "Fitz and the Tantrums", "2016", "Fanmade", "Just Dance Now", "Handclapfan"));
        Chocolist.Add(new SongInfo("Stadium Flow ALT", "Imposs", "2015", "Fanmade", "Just Dance Now", "Stadiumflowfan"));
        Chocolist.Add(new SongInfo("This Is How We Do ALT", "Katy Perry", "2013", "Fanmade", "Just Dance Now", "Thisishowfan"));
        Chocolist.Add(new SongInfo("Turn Up the Love ALT", "Far East Movement ft. Cover Drive", "2012", "Fanmade", "Just Dance Now", "Turnupthelovefan"));
        Chocolist.Add(new SongInfo("We No Speak Americano ALT", "Yolanda Be Cool and DCUP (Hit the Electro Beat)", "2010", "Fanmade", "Just Dance Now", "Americanofan"));
        Chocolist.Add(new SongInfo("All About That Bass ALT", "Meghan Trainor", "2014", "Flower & Bee", "Just Dance 2016", "Aboutthatbassalt_cover_generic"));
        Chocolist.Add(new SongInfo("Animals ALT", "Martin Garrix", "2013", "Extreme", "Just Dance 2016", "AnimalsALT"));
        Chocolist.Add(new SongInfo("Born This Way ALT", "Lady Gaga", "2011", "Nerd", "Just Dance 2016", "BornThisWayALT"));
        Chocolist.Add(new SongInfo("Circus ALT", "Britney Spears", "2008", "Extreme", "Just Dance 2016", "CircusALT"));
        Chocolist.Add(new SongInfo("Fancy ALT", "Iggy Azalea ft. Charli XCX", "2014", "Indian", "Just Dance 2016", "Fancyalt_cover_generic"));
        Chocolist.Add(new SongInfo("Hey Mama ALT", "David Guetta ft. Nicki Minaj, Bebe Rexha, & Afrojack", "2014", "Geisha", "Just Dance 2016", "HeyMamaALT"));
        Chocolist.Add(new SongInfo("Hit The Road Jack ALT", "Ray Charles (Charles Percy)", "1961", "Line Dance", "Just Dance 2016", "HitTheRoadALT"));
        Chocolist.Add(new SongInfo("I Gotta Feeling ALT", "The Black Eyed Peas", "2009", "School", "Just Dance 2016", "IGotAFeelingALT"));
        Chocolist.Add(new SongInfo("Rabiosa ALT", "Shakira Ft. El Cata", "2010", "Latin Fitness/Sweat", "Just Dance 2016", "Rabiosaalt"));
        Chocolist.Add(new SongInfo("Teacher ALT", "Nick Jonas", "2014", "Car Version", "Just Dance 2016", "TeacherALT"));
        Chocolist.Add(new SongInfo("This Is How We Do ALT", "Katy Perry", "2013", "Aerobics/Sweat", "Just Dance 2016", "Thisishowalt"));
        Chocolist.Add(new SongInfo("Uptown Funk ALT", "Mark Ronson ft. Bruno Mars", "2014", "Tuxedo", "Just Dance 2016", "UptownFunkALT"));
        Chocolist.Add(new SongInfo("Want To Want Me ALT", "Jason Derulo", "2015", "Couple Version", "Just Dance 2016", "WantToWantMeALT"));
        Chocolist.Add(new SongInfo("Cake By The Ocean ALT", "DNCE", "2015", "Earphones", "Just Dance 2017", "Cakebytheoceanalt_cover_generic"));
        Chocolist.Add(new SongInfo("Cheap Thrills ALT", "Sia Ft. Sean Paul", "2016", "Bollywood", "Just Dance 2017", "Cheapthrillsalt"));
        Chocolist.Add(new SongInfo("Chiwawa ALT", "Wanko Ni Mero Mero", "2015", "Remastered By Barbie", "Just Dance 2017", "Barbie_cover_generic"));
        Chocolist.Add(new SongInfo("Cola Song ALT", "INNA ft. J Balvin", "2014", "Candy", "Just Dance 2017", "Colasongalt_cover_generic"));
        Chocolist.Add(new SongInfo("Don’t Stop Me Now ALT", "Queen", "1979", "Panda", "Just Dance 2017", "Dontstopmealt"));
        Chocolist.Add(new SongInfo("El Tiki ALT", "Maluma", "2015", "Trio", "Just Dance 2017", "Eltikialt"));
        Chocolist.Add(new SongInfo("Hips Don’t Lie ALT", "Shakira ft. Wyclef Jean", "2005", "Sumo", "Just Dance 2017", "Hipsalt"));
        Chocolist.Add(new SongInfo("Lean On ALT", "Major Lazer ft. MØ & DJ Snake", "2015", "Scarf", "Just Dance 2017", "Leanonalt"));
        Chocolist.Add(new SongInfo("RADICAL ALT", "Dyro & Dannic", "2014", "Helmet", "Just Dance 2017", "Radicalalt"));
        Chocolist.Add(new SongInfo("September ALT", "Earth, Wind & Fire (Equinox Stars)", "1978 (2016)", "Disco Fitness/Sweat", "Just Dance 2017", "Septemberalt"));
        Chocolist.Add(new SongInfo("Sorry ALT", "Justin Bieber", "2015", "Extreme", "Just Dance 2017", "Sorryalt"));
        Chocolist.Add(new SongInfo("What Is Love ALT", "Haddaway (Ultraclub 90)", "1993", "Car Version", "Just Dance 2017", "Whatislovealt_cover_generic"));
        Chocolist.Add(new SongInfo("Watch Me (Whip/Nae Nae) ALT", "Silento", "2015", "Family Battle", "Just Dance 2017", "Naenaealt"));
        Chocolist.Add(new SongInfo("Wake Me Up Before You Go-Go ALT", "Wham!", "1984", "From The Emoji Movie", "Just Dance 2017", "WakeMeUpALT_Cover_Generic"));
        Chocolist.Add(new SongInfo("Worth It ALT", "Fifth Harmony ft. Kid Ink", "2015", "Extreme Crew", "Just Dance 2017", "Worthitalt"));
        Chocolist.Add(new SongInfo("24K Magic ALT", "Bruno Mars", "2016", "Extreme Version", "Just Dance 2018", "24kalt_cover_generic"));
        Chocolist.Add(new SongInfo("Another One Bites the Dust ALT", "Queen", "1980", "Stunt Version", "Just Dance 2018", "Anotheronealt_cover_generic"));
        Chocolist.Add(new SongInfo("Automaton ALT", "Jamiroquai", "2017", "Tomato Version", "Just Dance 2018", "Automatonalt_cover_generic"));
        Chocolist.Add(new SongInfo("Bubble Pop! ALT", "Hyuna", "2011", "Bubble Gum Version", "Just Dance 2018", "Bubblepopalt_cover_generic"));
        Chocolist.Add(new SongInfo("Chantaje ALT", "Shakira ft. Maluma", "2016", "Subway Version", "Just Dance 2018", "Chantajealt_cover_generic"));
        Chocolist.Add(new SongInfo("Despacito ALT", "Luis Fonsi & Daddy Yankee", "2017", "Extreme Version", "Just Dance 2018", "Despacitoalt_cover_generic"));
        Chocolist.Add(new SongInfo("Dharma ALT", "Headhunterz & KSHMR", "2016", "Fight Version", "Just Dance 2018", "Dharmaalt_cover_generic"));
        Chocolist.Add(new SongInfo("Footloose ALT", "Kenny Loggin (Top Culture)", "Solo", "Kids Mode", "Just Dance 2018 (Kids Mode)", "Footloosekids_cover_generic"));
        Chocolist.Add(new SongInfo("John Wayne ALT", "Lady Gaga", "2016", "Extreme Version", "Just Dance 2018", "Johnwalt_cover_generic"));
        Chocolist.Add(new SongInfo("Kissing Strangers ALT", "DNCE ft. Nicki Minaj", "2017", "Charleston Version", "Just Dance 2018", "Kissingstrangersalt_cover_generic"));
        Chocolist.Add(new SongInfo("Side to Side ALT", "Ariana Grande ft. Nicki Minaj", "2016", "Cycling Version", "Just Dance 2018", "Sidetoalt_cover_generic"));
        Chocolist.Add(new SongInfo("Tumbum ALT", "Yemi Alade", "2016", "Extreme Version", "Just Dance 2018", "Tumbumalt_cover_generic"));
        Chocolist.Add(new SongInfo("Waka Waka (This Time for Africa) ALT", "Shakira", "2010", "Football Version", "Just Dance 2018", "Wakawakaalt_cover_generic"));
        Chocolist.Add(new SongInfo("Waka Waka (This Time for Africa) ALT", "Shakira", "2010", "Kids Mode", "Just Dance 2018 (Kids Mode)", "Wakawakakids_cover_generic"));
        Chocolist.Add(new SongInfo("Bang Bang Bang ALT", "BIGBANG", "2015", "Fanmade", "Just Dance Unlimited", "Bang2019VIP_Cover_Generic"));
        Chocolist.Add(new SongInfo("Bum Bum Tam Tam ALT", "MC Fioti, Future, J Balvin, Stefflon Don, Juan Magan", "2018", "Mad Scientist Version", "Just Dance 2019", "Bumbumtamtamalt_cover_generic"));
        Chocolist.Add(new SongInfo("Swish Swish ALT", "Katy Perry ft. Nicki Minaj", "2017", "VIPmade", "Just Dance Unlimited", "swishswishALT"));
        Chocolist.Add(new SongInfo("Alphabet Song Kids", "The Just Dance Kids", "Traditional", "Solo", "Just Dance Kids", "Kidsabc"));
        Chocolist.Add(new SongInfo("If You’re Happy and You Know It Kids", "The Just Dance Kids", "Traditional", "Solo", "Just Dance Kids", "KIDSIfYoureHappy_cover_generic"));
        Chocolist.Add(new SongInfo("I’ve Been Working on The Railroad Kids", "The Just Dance Kids", "Traditional", "Solo", "Just Dance Kids", "KIDSWorkingOnTheRailroad_Cover_Generic"));
        Chocolist.Add(new SongInfo("Wheels on The Bus Kids", "The Just Dance Kids", "2010", "Solo", "Just Dance Kids", "KIDSWheelsOnTheBus_Cover_Generic"));
        Chocolist.Add(new SongInfo("Accidentally in Love Kids", "Counting Crows", "2004", "Solo", "Just Dance Kids 2", "KIDSAccidentallyInLove_cover_generic"));
        Chocolist.Add(new SongInfo("Five Little Monkeys Kids", "The Just Dance Kids", "Traditional", "Solo", "Just Dance Kids 2", "Kidsfivelittlemonkeys_cover_generic"));
        Chocolist.Add(new SongInfo("The Lion Sleeps Tonight Kids", "The Just Dance Kids", "1961", "Solo", "Just Dance Kids 2", "Kidsthelionsleepstonight_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Jingle Bells Kids", "The Just Dance Kids", "1857", "Solo", "Just Dance Kids 2", "Kidsjinglebells"));
        Chocolist.Add(new SongInfo("A Pirate You Shall Be Kids", "Tom Zehnder", "1996", "Solo", "Just Dance Kids 2014", "KIDSPirateYouShallBe_Cover_Generic.tga"));
        Chocolist.Add(new SongInfo("Day-O (The Banana Boat Song) Kids", "Harry Belafonte (The Just Dance Kids)", "1956 (2013)", "Solo", "Just Dance Kids 2014", "KIDSDayO_Cover_Generic"));
        Chocolist.Add(new SongInfo("Fraggle Rock Kids", "The Just Dance Kids", "1983", "Solo", "Just Dance Kids 2014", "Kidsfragglerock_cover_generic"));
        Chocolist.Add(new SongInfo("Hickory Dickory Dock Kids", "Tom Zehnder", "2007", "Solo", "Just Dance Kids 2014", "KIDSHickoryDickoryDock_Cover_Generic.tga"));
        Chocolist.Add(new SongInfo("I Like To Move It Kids", "The Just Dance Kids", "1993", "Solo", "Just Dance Kids 2014", "Kidsiliketomoveit"));
        Chocolist.Add(new SongInfo("Mary Had A Little Lamb Kids", "Tom Zehnder", "1830", "Solo", "Just Dance Kids 2014", "KIDSMaryHadALittleLamb_Cover_Generic.tga"));
        Chocolist.Add(new SongInfo("We Go Well Together Kids", "Goldheart", "2003", "Solo", "Just Dance Kids 2014", "KIDSWeGoWellTogether_Cover_Generic.tga"));
        Chocolist.Add(new SongInfo("Dancing Queen (Dancefloor Version)", "ABBA", "1976", "Solo", "ABBA: You Can Dance", "Abbadancingqueen_thumb@2x"));
        Chocolist.Add(new SongInfo("Fernando", "ABBA", "1974", "Duet", "ABBA: You Can Dance", "Abbafernando"));
        Chocolist.Add(new SongInfo("Gimme! Gimme! Gimme! (A Man After Midnight)", "ABBA", "1979", "Solo", "ABBA: You Can Dance", "Abbagimmegimme_jdnow_cover_generic"));
        Chocolist.Add(new SongInfo("Honey, Honey", "ABBA", "1974", "Dance Crew", "ABBA: You Can Dance", "Abbahoneyhoney"));
        Chocolist.Add(new SongInfo("Knowing Me, Knowing You", "ABBA", "1977", "Dance Crew", "ABBA: You Can Dance", "Abbaknowingme_cover_generic"));
        Chocolist.Add(new SongInfo("Lay All Your Love On Me", "ABBA", "1981", "Solo", "ABBA: You Can Dance", "Abbalayallyourlove"));
        Chocolist.Add(new SongInfo("Mamma Mia", "ABBA", "1975", "Dance Crew", "ABBA: You Can Dance", "Abbamammamia_Cover_Generic"));
        Chocolist.Add(new SongInfo("Money, Money, Money", "ABBA", "1976", "Solo", "ABBA: You Can Dance", "Abbamoneymoney_cover_generic"));
        Chocolist.Add(new SongInfo("SOS", "ABBA", "1975", "Duet", "ABBA: You Can Dance", "Abbasos_cover_generic"));
        Chocolist.Add(new SongInfo("Super Trouper", "ABBA", "1980", "Solo", "ABBA: You Can Dance", "Abbasupertrooper_cover_generic"));
        Chocolist.Add(new SongInfo("Take A Chance On Me", "ABBA", "1978", "Duet", "ABBA: You Can Dance", "Abbatakeachancea_Cover_Generic"));
        Chocolist.Add(new SongInfo("The Winner Takes It All", "ABBA", "1980", "Solo", "ABBA: You Can Dance", "Abbathewinner"));
        Chocolist.Add(new SongInfo("Voulez-Vous", "ABBA", "1979", "Solo", "ABBA: You Can Dance", "Abbavoulezvous_cover_generic"));
        Chocolist.Add(new SongInfo("Waterloo", "ABBA", "1974", "Dance Crew", "ABBA: You Can Dance", "Abbawaterloo"));
        Chocolist.Add(new SongInfo("Sweet Sensation", "Flo Rida", "2018", "Quartet", "Just Dance 2019", "Sweetsensation_cover_generic"));
        Chocolist.Add(new SongInfo("Milosc W Zakopanem", "Slawomir", "2017", "Solo", "Just Dance 2019", "Miloscw_cover_generic"));
        Chocolist.Add(new SongInfo("Not Your Ordinary", "Stella Mwangi", "2017", "Quartet", "Just Dance 2019", "Notyourordinary_cover_generic"));
        //added 16.05.19
        Chocolist.Add(new SongInfo("DDU-DU DDU-DU", "BLACKPINK", "2018", "Dance Crew", "Just Dance 2019", "Ddudu_jd2019_gameplay"));
        Chocolist.Add(new SongInfo("A Little Party Never Killed Nobody (All We Got)", "Fergie ft. Q-Tip & GoonRock", "2013", "Solo", "Just Dance 2019", "Alittlepartyneverkillednobody_jd2019_gameplay"));
        //added 24.05.19
        Chocolist.Add(new SongInfo("Un Poco Loco", "Anthony Gonzalez and Gael García Bernal", "2017", "Solo", "Just Dance 2019", "Pocoloco_cover_generic"));
        Chocolist.Add(new SongInfo("TOY", "Netta", "2018", "Solo", "Just Dance 2019", "Toy_cover_generic"));


    }
}
